---
###############################################################################
# Firmware Upgrades
###############################################################################
# Upgrade any firmware on system and reboot.
#
# Manual firmware update (requires reboot if changes):
#
#   fwupdmgr get-devices
#   fwupdmgr refresh
#   fwupdmgr get-updates
#   fwupdmgr update
#
# Reference:
# * https://wiki.archlinux.org/title/Fwupd
# * https://manpages.debian.org/unstable/fwupd/fwupdmgr.1.en.html

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ firmware___packages }}'
      - '{{ firmware_srv_packages }}'
    apt_packages_absent:
      - '{{ firmware_srv_packages_absent }}'
    apt_sources: '{{ firmware_srv_apt_sources }}'
    apt_srv_package_update_cache: true

- name: 'Upgrade | cmd | refresh metadata'
  ansible.builtin.command:
    argv:
      - '/usr/bin/fwupdmgr'
      - 'refresh'
      - '--force'
      - '--assume-yes'
  changed_when: false

- name: 'Upgrade | cmd | check for updates'
  ansible.builtin.command:
    argv:
      - '/usr/bin/fwupdmgr'
      - 'get-updates'
      - '--json'
      - '--assume-yes'
  register: firmware__check
  changed_when: false

- name: 'Upgrade | fact | parse update list'
  ansible.builtin.set_fact:
    firmware__check_json: '{{ firmware__check.stdout | from_json }}'

- name: 'Upgrade | updates found'
  when: firmware__check_json.Devices | length > 0
  block:
    - name: 'Upgrade | cmd | apply updates'
      ansible.builtin.command:
        argv:
          - '/usr/bin/fwupdmgr'
          - 'update'
          - '--offline'
          - '--no-reboot-check'
          - '--assume-yes'
      become: true
      register: firmware__reboot
      changed_when: true

    - name: 'Upgrade | reboot (~2 minutes) 🗘'
      when: firmware__reboot.rc == 0
      ansible.builtin.reboot:
        msg: |

          Rebooting to apply firmware updates (~2 minutes).

      async: '{{ firmware_srv_timeout | default(firmware___app._timeout) }}'
      poll: '{{ firmware_srv_poll | default(firmware___app._poll) }}'
