---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Converge | apply r_pufky.deb.firmware'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.firmware'
