---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Verify | gather installed packages'
      ansible.builtin.package_facts:

    - name: 'Verify | assert firmware package installed'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"fwupd" in ansible_facts.packages'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                    fwupd should be installed.                     │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
